# Generated by Django 3.2.14 on 2022-07-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooker', '0003_alter_event_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_attendees',
            field=models.IntegerField(null=True),
        ),
    ]
