# Generated by Django 3.2.14 on 2022-08-01 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventbooker', '0004_event_max_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='scheduled_time',
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='booker', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='eventbooker.event')),
                ('timeslot', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='eventbooker.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='timeslots',
            field=models.ManyToManyField(blank=True, related_name='times', to='eventbooker.Timeslot'),
        ),
    ]
