# Generated by Django 3.2.14 on 2022-08-01 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooker', '0006_auto_20220801_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='timeslots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='times', to='eventbooker.timeslot'),
        ),
    ]
