# Generated by Django 3.2.14 on 2022-08-02 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooker', '0007_event_timeslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='timeslots',
        ),
    ]
