# Generated by Django 3.2.14 on 2022-08-02 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventbooker', '0008_remove_event_timeslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attending_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
