# Generated by Django 3.2.14 on 2022-08-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooker', '0009_auto_20220802_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
