# Generated by Django 3.2.14 on 2022-08-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooker', '0012_rename_timeslot_eventtimeslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtimeslot',
            name='user_attending',
            field=models.BooleanField(default=False),
        ),
    ]
