# Generated by Django 3.2.14 on 2022-08-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooker', '0013_eventtimeslot_user_attending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtimeslot',
            name='user_attending',
        ),
    ]
