# Generated by Django 3.2.14 on 2022-08-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventbooker', '0016_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Username', max_length=30),
        ),
    ]
